### ISSUE TITLE
Wildcard asset registration

### ISSUE THREAD

**Issue by HamAndRock** [baraja-core/assets-loader#1]
Please add support for * character in assetLoader routing, for easier assets management.

Example:

assetsLoader:
	routing:
	      'Admin:\*': 
			- vue/category/eventbus.js
 	      'Admin:Category:\*':
			- vue/category/eventbus2.js

**Comment by janbarasek** [comment]
@HamAndRock Thanks!

I added native support for syntax:

- `*`
- `Admin:*`
- `Admin:Homepage:*`
- `Admin:Homepage:default`

Commit: https://github.com/baraja-core/assets-loader/commit/03c2a871e63883aba2a57ade0091d7b258ba6140

During the implementation, I improved the performance of the DIC compilation.
